asyncapi: 2.6.0
info:
  title: Product audits API 6
  version: '1.0.0'
channels:
  demo.products:
    publish:
      operationId: publishProducts
      message:
        $ref: "#/components/messages/Product"
  demo.tasks:
    subscribe:
      operationId: getTasks
      message:
        $ref: "#/components/messages/Task"

components:
  messages:
    Product:
      name: product
      title: An inventory product
      summary: Product representing items in inventory
      contentType: application/json
      payload:
        type: object
        properties:
          name:
            description: Every product has a name
            type: string
          inventory:
            description: Count of items in inventory
            type: number
          id:
            description: Unique identifier of the product
            type: number
      examples:
        - name: SUCCESS
          payload:
            name: "Vision Pro"
            inventory: 10
            id: 123
    Task:
      name: Task
      title: A Task to be processed
      summary: Inform about a new user task in the system
      contentType: application/json
      payload:
        type: object
        required:
          - name
        properties:
          name:
            type: string
      examples:
        - name: SUCCESS
          payload:
            name: "Vision Pro Task"

