{
  "formatVersion": "1.1",
  "component": {
    "group": "io.specmatic",
    "module": "specmatic-googlepubsub",
    "version": "0.1.3-TRIAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-googlepubsub-0.1.3-TRIAL.jar",
          "url": "specmatic-googlepubsub-0.1.3-TRIAL.jar",
          "size": 229973,
          "sha512": "98b42b532df40f16e632963dfe9d620dd792d922dd17d64601641450bf4dab8b111a2df0744d74e233fa08bdf9254500588bb2eae72b19289abe54513ce2de33",
          "sha256": "669e3c408c2d55a57950ab8bf858e68dc5b88b5dcf969c89f2e3d1408e4be0f1",
          "sha1": "6ab7c9c0ae46f83786cf88c03137e6100d9a2bfd",
          "md5": "b536e2f8ef69865b945a9d8494f475ea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.cloud",
          "module": "libraries-bom",
          "version": {
            "requires": "26.32.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.cloud",
          "module": "google-cloud-pubsub"
        },
        {
          "group": "com.asyncapi",
          "module": "asyncapi-core",
          "version": {
            "requires": "1.0.0-RC2"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.core",
              "module": "jackson-databind"
            },
            {
              "group": "com.fasterxml.jackson.module",
              "module": "jackson-module-kotlin"
            },
            {
              "group": "com.fasterxml.jackson.dataformat",
              "module": "jackson-dataformat-yaml"
            }
          ]
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.24.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-nop",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "io.specmatic",
          "module": "specmatic-core",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.15.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.15.3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-googlepubsub-0.1.3-TRIAL.jar",
          "url": "specmatic-googlepubsub-0.1.3-TRIAL.jar",
          "size": 229973,
          "sha512": "98b42b532df40f16e632963dfe9d620dd792d922dd17d64601641450bf4dab8b111a2df0744d74e233fa08bdf9254500588bb2eae72b19289abe54513ce2de33",
          "sha256": "669e3c408c2d55a57950ab8bf858e68dc5b88b5dcf969c89f2e3d1408e4be0f1",
          "sha1": "6ab7c9c0ae46f83786cf88c03137e6100d9a2bfd",
          "md5": "b536e2f8ef69865b945a9d8494f475ea"
        }
      ]
    }
  ]
}
