{
  "formatVersion": "1.1",
  "component": {
    "group": "io.specmatic",
    "module": "specmatic-googlepubsub",
    "version": "0.1.1-TRIAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-googlepubsub-0.1.1-TRIAL.jar",
          "url": "specmatic-googlepubsub-0.1.1-TRIAL.jar",
          "size": 113006,
          "sha512": "6c2aa4038fb894e83303a8352a22bb9883f0b6d1a913c5bbfb19ad2fa2b0ade19907484171e2afc0bdd7138fa79f3abb30e3ebad2e23bb10d2405c26b9729c72",
          "sha256": "1c6aae603701d71c1164778a7e02661ee66faf2429533d63694b11bf15cac903",
          "sha1": "a399a2390bf601d0b0fd10a928fac8836d330233",
          "md5": "dbf48030b0d659aa9e5a9a27a97d0630"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.cloud",
          "module": "libraries-bom",
          "version": {
            "requires": "26.32.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.cloud",
          "module": "google-cloud-pubsub"
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "com.asyncapi",
          "module": "asyncapi-core",
          "version": {
            "requires": "1.0.0-EAP-3"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.24.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-nop",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "io.specmatic",
          "module": "specmatic-core",
          "version": {
            "requires": "2.0.27"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.16.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.15.3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-googlepubsub-0.1.1-TRIAL.jar",
          "url": "specmatic-googlepubsub-0.1.1-TRIAL.jar",
          "size": 113006,
          "sha512": "6c2aa4038fb894e83303a8352a22bb9883f0b6d1a913c5bbfb19ad2fa2b0ade19907484171e2afc0bdd7138fa79f3abb30e3ebad2e23bb10d2405c26b9729c72",
          "sha256": "1c6aae603701d71c1164778a7e02661ee66faf2429533d63694b11bf15cac903",
          "sha1": "a399a2390bf601d0b0fd10a928fac8836d330233",
          "md5": "dbf48030b0d659aa9e5a9a27a97d0630"
        }
      ]
    }
  ]
}
